### ISSUE TITLE
Palbreak not working

### ISSUE THREAD

**Issue by swifymart** [sharedRoutine/PalBreak#2]
Palbreak tweak no longer working. Downloaded earlier versions of the iOS PayPal app and it still don't work. Also tried different Cydia tweaks for PayPal and the same problem. Don't know if PayPal changed or added their jailbreak detection? Running on a Phoenix jailbroken iPhone 4S.

**Comment by swifymart** [comment]
Fixed. JODebox 3.0.6 tweak was the culprit. Palbreak working again.

**Comment by tyhallcsu** [comment]
Anyway to keep JOdebox AND still have PayPal work? Or disable JOdebox only when opening PayPal?

**Comment by swifymart** [comment]
Downgrade to JODebox v 3.0.4. Both will work. You can download file from here:

http://files11.thebigboss.org/repofiles/cydia/debs2.0/jodebox_3.0.4.deb

**Comment by tyhallcsu** [comment]
Thanks, confirmed working!
